[tool.black]
line-length = 88
target-version = ['py310']
include = '\.py$'
exclude = '/(\.venv|venv|\.env|env|migrations)/'
skip-string-normalization = true

[tool.pytest.ini_options]
python_files = ["tests.py", "test_*.py"]
filterwarnings = "error"
addopts = '''
  --strict-markers
  --asyncio-mode=auto
  --doctest-modules
'''
doctest_optionflags = 'NORMALIZE_WHITESPACE IGNORE_EXCEPTION_DETAIL'
